### ISSUE TITLE
"Your RedPitaya currently offline." even though I can reach the Internet.

### ISSUE THREAD

**Issue by fossum** [RedPitaya/RedPitaya#226] opened 2022-01-12 15:11 UTC
The web interface seems fine and I can ping google.com from the terminal, but I cannot use the OS Update.
![image](https://user-images.githubusercontent.com/448582/149166928-ebc226d7-1924-4a57-b333-2091d57de7a2.png)

**Version:** STEMlab_125-xx_OS_1.04-9_stable
```
root@rp-f008ae:~# ping google.com
PING google.com (142.251.33.110) 56(84) bytes of data.
64 bytes from sea30s10-in-f14.1e100.net (142.251.33.110): icmp_seq=1 ttl=118 time=14.4 ms
64 bytes from sea30s10-in-f14.1e100.net (142.251.33.110): icmp_seq=2 ttl=118 time=14.3 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 14.313/14.365/14.418/0.130 ms
root@rp-f008ae:~#
```

**Side note:** The link for help is broken. Currently it points to http://redpitaya.com/quick-start/

**Comment by b-swat** [comment] 2022-01-13 06:04
Hello.
The problem is that at the end of September 2021, the root certificate expired because of this, some network functionality does not work.
You will need to write a new version of Linux to a USB flash drive and update the ecosystem.
https://downloads.redpitaya.com/downloads/LinuxOS/
Required version 1.06

or use the beta version
https://downloads.redpitaya.com/downloads/STEMlab-125-1x/STEMlab_125-xx_OS_1.04-11_beta.img.zip
Linux version 1.06 is already in use

**Comment by b-swat** [comment] 2022-01-13 06:14
> **Side note:** The link for help is broken. Currently it points to http://redpitaya.com/quick-start/

Thx. Will be fixed in next release.

**Closed** 2022-01-14 06:30 UTC
